@@include("../../blocks/modules/header/header.js")
@@include("../../blocks/modules/modals/modals.js")
@@include("../../blocks/modules/main-burger/main-burger.js")
@@include("../../blocks/modules/home-intro/home-intro.js")
@@include("../../blocks/modules/category-slider/category-slider.js")
@@include("../../blocks/modules/volume-slider/volume-slider.js")
@@include("../../blocks/modules/animal-slider/animal-slider.js")
@@include("../../blocks/modules/history-modal/history-modal.js")
@@include("../../blocks/modules/sp-slider/sp-slider.js")
@@include("../../blocks/modules/product-slider/product-slider.js")
@@include("../../blocks/modules/tabs-block/tabs-block.js")
@@include("../../blocks/modules/contacts-intro/contacts-intro.js")

document.addEventListener('DOMContentLoaded', () => {
  homeIntro()
  modalsInit()
  mainBurger()
  categorySlider()
  volumeSlider()
  animalSlider()
  historyModal()
  spSlider()
  productSlider()
  tabsBlockInit()
  contactsController()
})